name: Update Submodules

on:
    repository_dispatch:
        types: [update-submodules]
    workflow_dispatch:

jobs:
    update-submodules:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  submodules: true
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Update submodules to latest commit
              run: |
                  git submodule update --init --recursive
                  git submodule update --recursive --remote
                  git config --global user.email "submodules-updater[bot]@users.noreply.github.com"
                  git config --global user.name "submodules-updater[bot]"
                  git add .

                  if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
                    git commit -m "Manual submodule update"
                  else
                    git commit -m "Auto-update submodule: ${{ github.event.client_payload.source_repo }} - (${{ github.event.client_payload.commit_hash }}) ${{ github.event.client_payload.commit_message }}"
                  fi

                  git push

            - name: Trigger site rebuild
              uses: peter-evans/repository-dispatch@v2
              with:
                  token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                  repository: ${{ github.repository }}
                  event-type: build-site
